;<?php die('');?>
isWindows=1
enableAllModules=
disableInstallers=
chmodDir=509
chmodFile=436
forceHTTPSPort=
forceHTTPPort=
fallbackLocale=
domainName=localhost
modulesPath="lib:jelix-admin-modules/,lib:jelix-modules/,app:modules/"
pluginsPath="app:plugins/,lib:jelix-plugins/,module:jacl2,module:jacl2db"
timeZone="Europe/Paris"
httpVersion=
theme=default
charset=UTF-8
locale=fr_FR
startAction="dashboard:index"
startModule=dashboard
[availableLocales]
0=fr_FR
[modules]
jelix.access=2
jelix.path="lib:jelix/core-modules/jelix"
jacldb.access=0
jacl2db.access=2
jauth.access=2
jauthdb.access=2
junittests.access=0
jsoap.access=0
pagesjaunes_core.access=2
user.access=2
acl2.access=2
acl2db.access=2
authdb.access=2
common.access=2
dashboard.access=2
profile.access=2
right.access=2
slideshow.access=2
categorie.access=2
homepage.access=2
entreprise.access=2
front_office.access=2
catalogue.access=2
toprecherche.access=2
pages.access=2
search.access=2
ads.access=2
jacl.access=0
master_admin.access=2
jauthdb.installparam=defaultuser
jauthdb_admin.access=2
jacl2.access=2
jacl2db.installparam=defaultuser
jacl2db_admin.access=2
jpref.access=2
jpref_admin.access=2
jacl2db_admin.dbprofile=default
jauthdb_admin.dbprofile=default
jpref_admin.dbprofile=default
master_admin.dbprofile=default
jacl.dbprofile=default
jacl2.dbprofile=default
jacl2db.dbprofile=default
jacldb.dbprofile=default
jauth.dbprofile=default
jauthdb.dbprofile=default
jpref.dbprofile=default
jsoap.dbprofile=default
junittests.dbprofile=default
acl2db.dbprofile=default
ads.dbprofile=default
authdb.dbprofile=default
catalogue.dbprofile=default
categorie.dbprofile=default
common.dbprofile=default
dashboard.dbprofile=default
entreprise.dbprofile=default
front_office.dbprofile=default
homepage.dbprofile=default
pages.dbprofile=default
pagesjaunes_core.dbprofile=default
profile.dbprofile=default
right.dbprofile=default
search.dbprofile=default
slideshow.dbprofile=default
toprecherche.dbprofile=default
user.dbprofile=default
jelix.dbprofile=default
[coordplugins]
auth="admin/auth.coord.ini.php"
jacl2=1
[tplplugins]
defaultJformsBuilder=html
[responses]
html=adminHtmlResponse
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=adminLoginHtmlResponse
sitemap=jResponseSitemap
noheader=noheaderHtmlResponse
htmlforgotpassword=adminForgotPasswordHtmlResponse
html.path="G:\wamp\pagesjaunes_core/responses/adminHtmlResponse.class.php"
basichtml.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseBinary.class.php"
text.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseText.class.php"
cmdline.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseJsonrpc.class.php"
json.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseXmlrpc.class.php"
xml.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseXml.class.php"
zip.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseZip.class.php"
rss2.0.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseAtom10.class.php"
css.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseCss.class.php"
htmlfragment.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="G:\wamp\pagesjaunes_core/responses/adminLoginHtmlResponse.class.php"
sitemap.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseSitemap.class.php"
noheader.path="G:\wamp\pagesjaunes_core/responses/noheaderHtmlResponse.class.php"
htmlforgotpassword.path="G:\wamp\pagesjaunes_core/responses/adminForgotPasswordHtmlResponse.class.php"
[_coreResponses]
html=jResponseHtml
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
sitemap=jResponseSitemap
html.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseHtml.class.php"
basichtml.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseBinary.class.php"
text.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseText.class.php"
cmdline.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseJsonrpc.class.php"
json.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseXmlrpc.class.php"
xml.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseXml.class.php"
zip.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseZip.class.php"
rss2.0.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseAtom10.class.php"
css.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseCss.class.php"
htmlfragment.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseHtml.class.php"
sitemap.path="G:\wamp\jelix\lib_1_6_10_dev\jelix/core/response/jResponseSitemap.class.php"
[jResponseHtml]
plugins=
minifyEntryPoint=minify.php
minifyCSS=
minifyJS=
minifyExcludeCSS=
minifyExcludeJS="jelix/wymeditor/jquery.wymeditor.js"
[debugbar]
plugins="sqllog,sessiondata,defaultlog"
defaultPosition=right
errors_openon=error
[error_handling]
messageLogFormat="%date%\t%ip%\t[%code%]\t%msg%\t%file%\t%line%\n\t%url%\n%params%\n%trace%\n\n"
errorMessage="A technical error has occured (code: %code%). Sorry for this inconvenience."
[compilation]
checkCacheFiletime=1
force=
[urlengine]
engine=basic_significant
enableParser=1
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/pagesjaunes/"
backendBasePath=
checkHttpsOnParsing=1
jelixWWWPath="/pagesjaunes/jelix/"
jqueryPath="/pagesjaunes/jelix/jquery/"
defaultEntrypoint=index
notfoundAct="jelix~error:notfound"
simple_urlengine_https=
significantFile=urls.xml
urlScript="/pagesjaunes/admin.php"
urlScriptPath="/pagesjaunes/"
urlScriptName=admin.php
urlScriptId=admin
urlScriptIdenc=admin
documentRoot="G:\wamp\pagesjaunes_core/../www"
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
admin="jacl2db~*@classic, jauth~*@classic, jacl2db_admin~*@classic, jauthdb_admin~*@classic, master_admin~*@classic, jpref_admin~*@classic, user~*@classic, acl2db~*@classic, authdb~*@classic, dashboard~*@classic, profile~*@classic, right~*@classic, slideshow~*@classic, categorie~*@classic, homepage~*@classic, entreprise~*@classic, catalogue~*@classic, toprecherche~*@classic, pages~*@classic, ads~*@classic"
[basic_significant_urlengine_entrypoints]
index=1
xmlrpc=1
jsonrpc=1
admin=1
[logger]
_all=
default=file
error=file
warning=file
notice=file
deprecated=
strict=
debug=
sql=
soap=
[fileLogger]
default=messages.log
error=errors.log
warning=errors.log
notice=errors.log
deprecated=errors.log
strict=errors.log
debug=debug.log
[memorylogger]
default=20
error=10
warning=10
notice=10
deprecated=10
strict=10
debug=20
sql=20
soap=20
[mailLogger]
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
[syslogLogger]
facility=LOG_LOCAL7
ident="php-%sapi%-%domain%[%pid%]"
[mailer]
webmasterEmail="root@localhost"
webmasterName=
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
filesDir="mails/"
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
copyToFiles=
[acl]
driver=
[acl2]
driver=db
[sessions]
start=1
shared_session=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.datetime.months.labels=names
datepicker=default
[jforms_builder_html]
[datepickers]
default="jelix/js/jforms/datepickers/default/init.js"
[htmleditors]
default.engine.name=wymeditor
default.engine.file[]="jelix/jquery/jquery.js"
default.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
default.config="jelix/js/jforms/htmleditors/wymeditor_default.js"
default.skin.default="jelix/wymeditor/skins/default/skin.css"
wymbasic.engine.name=wymeditor
wymbasic.engine.file[]="jelix/jquery/jquery.js"
wymbasic.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
wymbasic.config="jelix/js/jforms/htmleditors/wymeditor_basic.js"
wymbasic.skin.default="jelix/wymeditor/skins/default/skin.css"
ckdefault.engine.name=ckeditor
ckdefault.engine.file[]="jelix/ckeditor/ckeditor.js"
ckdefault.config="jelix/js/jforms/htmleditors/ckeditor_default.js"
ckfull.engine.name=ckeditor
ckfull.engine.file[]="jelix/ckeditor/ckeditor.js"
ckfull.config="jelix/js/jforms/htmleditors/ckeditor_full.js"
ckbasic.engine.name=ckeditor
ckbasic.engine.file[]="jelix/ckeditor/ckeditor.js"
ckbasic.config="jelix/js/jforms/htmleditors/ckeditor_basic.js"
[wikieditors]
default.engine.name=wr3
default.wiki.rules=wr3_to_xhtml
default.engine.file="jelix/markitup/jquery.markitup.js"
default.config.path="jelix/markitup/sets/wr3/"
default.image.path="jelix/markitup/sets/wr3/images/"
default.skin="jelix/markitup/skins/simple/style.css"
[zones]
disableCache=
[classbindings]
[imagemodifier]
src_url=
src_path=
cache_url=
cache_path=
[rootUrls]
jelix.cache="cache/"
[langToLocale]
fr=fr_FR
[disabledListeners]
[coordplugin_auth]
persistant_crypt_key=TBCDW4er713irEk9UCTnDu0U8uljAu
[coordplugin_jacl2]
on_error=2
error_message="right~errors.action.right.needed"
on_error_action="right~error:badright"
[_allBasePath]
0="G:\wamp\jelix\lib_1_6_10_dev/jelix-admin-modules/"
1="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/"
2="G:\wamp\pagesjaunes_core/modules/"
3="G:\wamp\pagesjaunes_core/plugins/tpl/"
4="G:\wamp\jelix\lib_1_6_10_dev/jelix-plugins/cache/"
5="G:\wamp\jelix\lib_1_6_10_dev/jelix-plugins/kvdb/"
6="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2//plugins/coord/"
7="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2//plugins/tpl/"
8="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2db//plugins/acl2/"
[_modulesPathList]
jacl2db_admin="G:\wamp\jelix\lib_1_6_10_dev/jelix-admin-modules/jacl2db_admin/"
jauthdb_admin="G:\wamp\jelix\lib_1_6_10_dev/jelix-admin-modules/jauthdb_admin/"
jpref_admin="G:\wamp\jelix\lib_1_6_10_dev/jelix-admin-modules/jpref_admin/"
master_admin="G:\wamp\jelix\lib_1_6_10_dev/jelix-admin-modules/master_admin/"
jacl2="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2/"
jacl2db="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2db/"
jauth="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jauth/"
jauthdb="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jauthdb/"
jpref="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jpref/"
acl2db="G:\wamp\pagesjaunes_core/modules/acl2db/"
ads="G:\wamp\pagesjaunes_core/modules/ads/"
authdb="G:\wamp\pagesjaunes_core/modules/authdb/"
catalogue="G:\wamp\pagesjaunes_core/modules/catalogue/"
categorie="G:\wamp\pagesjaunes_core/modules/categorie/"
common="G:\wamp\pagesjaunes_core/modules/common/"
dashboard="G:\wamp\pagesjaunes_core/modules/dashboard/"
entreprise="G:\wamp\pagesjaunes_core/modules/entreprise/"
front_office="G:\wamp\pagesjaunes_core/modules/front_office/"
homepage="G:\wamp\pagesjaunes_core/modules/homepage/"
pages="G:\wamp\pagesjaunes_core/modules/pages/"
pagesjaunes_core="G:\wamp\pagesjaunes_core/modules/pagesjaunes_core/"
profile="G:\wamp\pagesjaunes_core/modules/profile/"
right="G:\wamp\pagesjaunes_core/modules/right/"
search="G:\wamp\pagesjaunes_core/modules/search/"
slideshow="G:\wamp\pagesjaunes_core/modules/slideshow/"
toprecherche="G:\wamp\pagesjaunes_core/modules/toprecherche/"
user="G:\wamp\pagesjaunes_core/modules/user/"
jelix="G:\wamp\jelix\lib_1_6_10_dev/jelix/core-modules/jelix/"
[_pluginsPathList_auth]
class="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/auth/class/"
db="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/auth/db/"
ldap="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/auth/ldap/"
lds="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/auth/lds/"
[_pluginsPathList_cache]
db="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/cache/db/"
memcache="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/cache/memcache/"
memcache22="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/cache/memcache22/"
redis="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/cache/redis/"
file="G:\wamp\jelix\lib_1_6_10_dev/jelix-plugins/cache/file/"
[_pluginsPathList_configcompiler]
debugbar="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/configcompiler/debugbar/"
locales="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/configcompiler/locales/"
nsautoloader="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/configcompiler/nsautoloader/"
responses="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/configcompiler/responses/"
session="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/configcompiler/session/"
[_pluginsPathList_coord]
auth="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/coord/auth/"
autolocale="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/coord/autolocale/"
history="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/coord/history/"
traceexec="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/coord/traceexec/"
zendframework="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/coord/zendframework/"
jacl2="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2//plugins/coord/jacl2/"
[_pluginsPathList_db]
mssql="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/db/mssql/"
mysql="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/db/mysql/"
mysqli="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/db/mysqli/"
oci="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/db/oci/"
pgsql="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/db/pgsql/"
sqlite="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/db/sqlite/"
sqlite3="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/db/sqlite3/"
[_pluginsPathList_debugbar]
defaultlog="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/debugbar/defaultlog/"
sessiondata="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/debugbar/sessiondata/"
soaplog="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/debugbar/soaplog/"
sqllog="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/debugbar/sqllog/"
[_pluginsPathList_formbuilder]
html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formbuilder/html/"
[_pluginsPathList_formwidget]
button_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/button_html/"
captcha_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/captcha_html/"
checkboxes_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/checkboxes_html/"
checkbox_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/checkbox_html/"
choice_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/choice_html/"
datetime_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/datetime_html/"
date_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/date_html/"
group_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/group_html/"
html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/html/"
htmleditor_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/htmleditor_html/"
input_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/input_html/"
listbox_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/listbox_html/"
menulist_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/menulist_html/"
output_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/output_html/"
radiobuttons_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/radiobuttons_html/"
reset_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/reset_html/"
secretconfirm_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/secretconfirm_html/"
secret_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/secret_html/"
submit_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/submit_html/"
textarea_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/textarea_html/"
upload_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/upload_html/"
wikieditor_html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/formwidget/wikieditor_html/"
[_pluginsPathList_htmlresponse]
debugbar="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/htmlresponse/debugbar/"
minify="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/htmlresponse/minify/"
[_pluginsPathList_jforms]
html="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/jforms/html/"
htmllight="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/jforms/htmllight/"
[_pluginsPathList_kvdb]
db="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/kvdb/db/"
dba="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/kvdb/dba/"
file2="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/kvdb/file2/"
memcache="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/kvdb/memcache/"
redis="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/kvdb/redis/"
file="G:\wamp\jelix\lib_1_6_10_dev/jelix-plugins/kvdb/file/"
[_pluginsPathList_logger]
firebug="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/logger/firebug/"
legacysyslog="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/logger/legacysyslog/"
[_tplpluginsPathList_common]
0="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2//plugins/tpl/common/"
1="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/tpl/common/"
[_tplpluginsPathList_html]
0="G:\wamp\pagesjaunes_core/plugins/tpl/html/"
1="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/tpl/html/"
[_tplpluginsPathList_ltx2pdf]
0="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_text]
0="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/tpl/text/"
[_tplpluginsPathList_xml]
0="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/tpl/xml/"
[_pluginsPathList_urls]
basic_significant="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/urls/basic_significant/"
significant="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/urls/significant/"
simple="G:\wamp\jelix\lib_1_6_10_dev\jelix/plugins/urls/simple/"
[_pluginsPathList_acl2]
db="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2db//plugins/acl2/db/"
dbcache="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2db//plugins/acl2/dbcache/"
[_autoload_class]
jAcl2="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2/classes/jAcl2.class.php"
jIAcl2Driver="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2/classes/jIAcl2Driver.iface.php"
jPref="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jpref/classes/jPref.php"
jPrefItem="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jpref/classes/jPrefItem.php"
jPrefItemGroup="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jpref/classes/jPrefItemGroup.php"
jPrefManager="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jpref/classes/jPrefManager.php"
[_autoload_namespace]
[_autoload_classpattern]
regexp[]="/^jAcl2Db/"
path[]="G:\wamp\jelix\lib_1_6_10_dev/jelix-modules/jacl2db/classes/|.class.php"
[_autoload_includepathmap]
[_autoload_includepath]
[_autoload_namespacepathmap]
[_autoload_autoloader]
